package edu.virginia.cs.hw2;

/**
 * An Exception generated by guesses being sent to a concluded Wordle game (either the
 * player has already won (guessed correctly) or lost (run out of guesses).
 * 
 * @author pm8fc
 */

@SuppressWarnings("serial")
public class GameOverException extends RuntimeException {
	/**
	 * Simple constructor for exception
	 * @param message - error message
	 */
	public GameOverException(String message) {
		super(message);
	}

}
